spring:
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/page/
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dj.ssm.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /
  port: 8080
